# Generated by Django 5.0.6 on 2024-06-08 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
      
        migrations.RemoveField(
            model_name='category',
            name='status',
        ),
        migrations.AddField(
            model_name='book',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='author_photos'),
        ),
        migrations.AddField(
            model_name='book',
            name='author_name',
            field=models.CharField(blank=True, default='Author Name', max_length=100, null=True, verbose_name='Author Name'),
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='books_photos'),
        ),
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(default=None, max_length=100, verbose_name='Book Name'),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Number Of Pages'),
        ),
        
       
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.BooleanField(choices=[('sold', 'sold'), ('Rented', 'Rented'), ('Available', 'Available')], default=None, max_length=50, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name',
            field=models.CharField(default=None, max_length=100, verbose_name='Category'),
        ),
    ]
