# Generated by Django 5.0.6 on 2024-06-08 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_remove_category_category_remove_category_name_and_more'),
    ]

    operations = [
     
    ]
