# Generated by Django 5.0.6 on 2024-06-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_alter_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Sold', 'Sold'), ('Rented', 'Rented'), ('Available', 'Available')], default=None, max_length=50, verbose_name='Status'),
        ),
    ]
