# Generated by Django 5.0.6 on 2024-06-10 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_alter_book_status'),
    ]

