# Generated by Django 5.0.6 on 2024-06-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_remove_book_retal_price_day_and_more'),
    ]

