# Generated by Django 5.0.6 on 2024-06-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_book_retal_choice_alter_book_retal_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Author Name'),
        ),
        
    ]
