# Generated by Django 5.0.3 on 2024-06-12 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_alter_book_author_name_alter_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='author_photos', verbose_name='Author Image'),
        ),
   
        
    ]
