# Generated by Django 5.0.3 on 2024-06-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0012_alter_book_author_image_alter_book_relation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(default=None, max_length=100, verbose_name=''),
        ),
    ]
