# Generated by Django 5.0.3 on 2024-06-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0014_alter_book_name_alter_category_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custmoer_name', models.CharField(default=None, max_length=50)),
                ('custmoer_email', models.EmailField(default=None, max_length=50)),
                ('message', models.TextField(default=None, max_length=500)),
            ],
        ),
    ]
