# Generated by Django 5.0.3 on 2024-06-15 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0015_contact_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='custmoer_email',
            field=models.EmailField(default=None, max_length=50, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='custmoer_name',
            field=models.CharField(default=None, max_length=50, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='message',
            field=models.TextField(default=None, max_length=500, verbose_name=''),
        ),
    ]
