# Generated by Django 5.0.3 on 2024-06-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0017_book_category'),
    ]

   