# Generated by Django 5.0.3 on 2024-06-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0018_book_total_price'),
    ]

    operations = [
        
       
    ]
