# Generated by Django 5.0.3 on 2024-06-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0019_remove_book_retal_price_day_book_retal_date_and_more'),
    ]

    operations = [
        
        
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('sold', 'Sold'), ('Rented', 'Rented'), ('Available', 'Available')], default=None, max_length=50, null=True, verbose_name='Status'),
        ),
    ]
