# Generated by Django 5.0.3 on 2024-06-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0020_remove_book_retal_price_day_book_retal_price_and_more'),
    ]

    operations = [
       
    ]
