# Generated by Django 5.0.3 on 2024-06-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0021_remove_book_retal_price_day_book_retal_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, verbose_name='Total Price'),
        ),
    ]
