# Generated by Django 5.0.3 on 2024-06-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0022_book_total_price'),
    ]

    operations = [
      
    
      
        migrations.AlterField(
            model_name='book',
            name='author_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(default=None, max_length=100, unique=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('sold', 'Sold'), ('Rented', 'Rented'), ('Available', 'Available')], default=None, max_length=50, null=True, verbose_name='Book Status'),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, verbose_name=''),
        ),
    ]
