# Generated by Django 5.0.3 on 2024-06-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0024_book_price_book_retal_date_book_retal_price_and_more'),
    ]

    operations = [
   
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('sold', 'Sold'), ('Rented', 'Rented'), ('Available', 'Available')], default=None, max_length=50, null=True, verbose_name='Book Status'),
        ),
    ]
