# Generated by Django 5.0.3 on 2024-06-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0029_book_price_book_retal_date_book_retal_price'),
    ]

    operations = [
        
        
    ]
