# Generated by Django 5.0.6 on 2024-06-23 10:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0031_book_price_book_retal_date_book_retal_price'),
    ]

    operations = [
  
    ]
