# Generated by Django 5.0.6 on 2024-06-23 12:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0033_merchant_profile_user_profile_book_add_book_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer_name', models.CharField(default=None, max_length=100, verbose_name='')),
                ('writer_password', models.CharField(default=None, max_length=100, unique=True, verbose_name='')),
            ],
        ),
 ]
