# Generated by Django 5.0.6 on 2024-06-23 13:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0034_login_merchant_profile_user_profile_and_more'),
    ]

    operations = [
     
    ]
