# Generated by Django 5.0.6 on 2024-06-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0036_alter_writer_profile_achievements_and_more'),
    ]

    operations = [
        
    ]
