# Generated by Django 5.0.6 on 2024-06-23 13:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0037_alter_writer_profile_achievements_and_more'),
    ]

    operations = [
   
    ]
