# Generated by Django 5.0.6 on 2024-06-23 13:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0040_merchant_profile_user_profile_book_add_book_date_and_more'),
    ]

    operations = [
        
    ]
