# Generated by Django 5.0.6 on 2024-06-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0042_delete_merchant_profile_delete_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='writer_name',
            new_name='writer_username',
        ),
    
    ]
