# Generated by Django 5.0.6 on 2024-06-23 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0043_rename_writer_name_login_writer_username_and_more'),
    ]
