# Generated by Django 5.0.6 on 2024-06-23 16:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0044_delete_merchant_profile_delete_user_profile'),
    ]

    

