# Generated by Django 5.0.6 on 2024-06-23 16:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0045_book_add_book_date_book_book_date_book_book_info_and_more'),
    ]

    

