# Generated by Django 5.0.6 on 2024-06-23 16:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0046_book_add_book_date_book_book_date_book_book_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='add_book_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='book',
            name='book_date',
            field=models.DateField(blank=True, null=True, verbose_name='Book Puplishe Date'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_info',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='book',
            name='retal_date',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='book',
            name='retal_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, verbose_name=''),
        ),
        migrations.CreateModel(
            name='Author_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer_name', models.CharField(default=None, max_length=100)),
                ('writer_password', models.CharField(default=None, max_length=100, unique=True)),
                ('writer_image', models.ImageField(blank=True, null=True, upload_to='author_photos', verbose_name='Profile Image')),
                ('writer_info', models.TextField(default=None, max_length=1000)),
                ('awardes', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('achievements', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('facebook_link', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('instagram_link', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('twitter_link', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('whatsapp_link', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('writer_books', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lms.book')),
            ],
        ),
    ]
