# Generated by Django 5.0.6 on 2024-06-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0047_book_add_book_date_book_book_date_book_book_info_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.AddField(
            model_name='author_profile',
            name='writer_email',
            field=models.EmailField(default=None, max_length=500),
        ),
    ]
