# Generated by Django 5.0.6 on 2024-06-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0049_alter_author_profile_writer_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author_profile',
            name='writer_email',
            field=models.EmailField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='author_profile',
            name='writer_info',
            field=models.TextField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='author_profile',
            name='writer_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='author_profile',
            name='writer_password',
            field=models.CharField(default=None, max_length=100, null=True, unique=True),
        ),
    ]
