# Generated by Django 5.0.6 on 2024-06-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0051_alter_author_profile_writer_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='author_profile',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
    ]
