# Generated by Django 5.0.6 on 2024-06-27 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0054_alter_author_profile_joined_date'),
    ]

 