# Generated by Django 5.0.6 on 2024-06-27 22:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0055_alter_author_profile_joined_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='author_profile',
            name='joined_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
