# Generated by Django 5.0.6 on 2024-06-27 22:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0056_author_profile_joined_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author_Profile',
            new_name='Profile',
        ),
    ]
