# Generated by Django 5.0.6 on 2024-06-30 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0057_rename_author_profile_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='writer_books',
            new_name='user',
        ),
    ]
