# Generated by Django 5.0.6 on 2024-06-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0060_alter_category_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(default=None, max_length=100, unique=True, verbose_name=''),
        ),
        migrations.DeleteModel(
            name='Author_Profile',
        ),
    ]
