# Generated by Django 5.0.6 on 2024-06-30 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0061_remove_book_author_alter_category_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer_name', models.CharField(default=None, max_length=100, null=True)),
                ('writer_email', models.EmailField(default=None, max_length=500, null=True)),
                ('writer_image', models.ImageField(blank=True, null=True, upload_to='author_photos', verbose_name='Profile Image')),
                ('writer_info', models.TextField(default=None, max_length=1000, null=True)),
                ('awardes', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('achievements', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('facebook_link', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('instagram_link', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('twitter_link', models.CharField(blank=True, default=None, max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lms.author_profile'),
            preserve_default=False,
        ),
    ]
