# Generated by Django 5.0.6 on 2024-06-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0062_author_profile_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='category',
            name='achievements',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='awardes',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='facebook_link',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='instagram_link',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='twitter_link',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='writer_email',
            field=models.EmailField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='writer_image',
            field=models.ImageField(blank=True, null=True, upload_to='author_photos', verbose_name='Profile Image'),
        ),
        migrations.AddField(
            model_name='category',
            name='writer_info',
            field=models.TextField(default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='writer_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Author_Profile',
        ),
    ]
