# Generated by Django 5.0.6 on 2024-07-02 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0063_remove_book_author_category_achievements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='category',
            name='awardes',
        ),
        migrations.RemoveField(
            model_name='category',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='category',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='category',
            name='twitter_link',
        ),
        migrations.RemoveField(
            model_name='category',
            name='writer_email',
        ),
        migrations.RemoveField(
            model_name='category',
            name='writer_image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='writer_info',
        ),
        migrations.RemoveField(
            model_name='category',
            name='writer_name',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
