# Generated by Django 5.0.6 on 2024-07-03 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0065_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author_image',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author_name',
        ),
    ]
