# Generated by Django 5.0.6 on 2024-07-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0068_remove_book_book_likes_book_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_info',
            field=models.TextField(blank=True, default=None, max_length=500, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='retal_date',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='retal_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True, verbose_name=''),
        ),
    ]
