# Generated by Django 5.0.6 on 2024-07-02 00:32

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, null=True)),
                ('email', models.EmailField(default=None, max_length=500, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='author_photos', verbose_name='Profile Image')),
                ('bio', models.TextField(default=None, max_length=1000, null=True)),
                ('facebook_link', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('instagram_link', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('twitter_link', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Slug')),
                ('joined_date', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
