# Generated by Django 5.0.6 on 2024-07-03 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_author_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author_profile',
            name='writer_email',
        ),
    ]
