# Generated by Django 5.0.6 on 2024-07-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_author_profile_writer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author_profile',
            name='achievements',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='author_profile',
            name='awardes',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='author_profile',
            name='facebook_link',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='author_profile',
            name='instagram_link',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='author_profile',
            name='twitter_link',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='author_profile',
            name='writer_info',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='author_profile',
            name='writer_name',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name=''),
        ),
    ]
