# Generated by Django 5.0.6 on 2024-07-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_author_profile_achievements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author_profile',
            name='writer_name',
            field=models.CharField(default=None, max_length=100, verbose_name=''),
        ),
    ]
