# Generated by Django 5.0.6 on 2024-07-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_author_profile_writer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linkedin_link',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
