# Generated by Django 5.0.6 on 2024-07-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_profile_linkedin_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=None, max_length=1000, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=None, max_length=500, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook_link',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram_link',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin_link',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter_link',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name=''),
        ),
    ]
