# Generated by Django 5.0.6 on 2024-07-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_profile_bio_alter_profile_facebook_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author_profile',
            name='linkedin_link',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='author_profile',
            name='achievements',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='author_profile',
            name='awardes',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='author_profile',
            name='facebook_link',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='author_profile',
            name='instagram_link',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='author_profile',
            name='twitter_link',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='author_profile',
            name='writer_info',
            field=models.TextField(blank=True, default=None, max_length=500, null=True, verbose_name=''),
        ),
    ]
